/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hammerdev_ihautoclicker_App */

#ifndef _Included_com_hammerdev_ihautoclicker_App
#define _Included_com_hammerdev_ihautoclicker_App
#ifdef __cplusplus
extern "C" {
#endif

jint JNI_OnLoad(JavaVM *vm, void *reserved);

/*
 * Class:     com_hammerdev_ihautoclicker_App
 * Method:    nativeMouseClick
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_github_imhammer_ihautoclicker_App_nativeMouseClick
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
